name: Main

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: blacha/hyperfine-action@master
      with:
        publish: true
